[development]
DEBUG = true

# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASES__default__ENGINE = "django.db.backends.sqlite3"
DATABASES__default__NAME = "db.sqlite3"

CHANNEL_LAYERS_HOSTS = "@merge [('localhost', 6379)]"

[production]
DEBUG = false
