[development]

DEBUG = true

DATABASES__default__ENGINE = "django.db.backends.sqlite3"
DATABASES__default__NAME = "db.sqlite3"

DICTDB_REDIS_HOST = 'localhost'
DICTDB_REDIS_PORT = 6379
DICTDB_REDIS_DB = 9
