# Generated by Django 3.0.7 on 2020-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('manager', 'manager'), ('seller', 'seller'), ('buyer', 'buyer'), ('both', 'both (sell and buy)')], db_index=True, max_length=30, verbose_name='role'),
        ),
    ]
