# Generated by Django 3.0.7 on 2020-06-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_attend',
            field=models.BooleanField(default=False, verbose_name='can attend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage',
            field=models.BooleanField(default=False, verbose_name='can manage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this profile should be treated as active. Unselect this instead of deleting profile.', verbose_name='active status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Designates whether the profile is from account owner.', verbose_name='owner status'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_sell',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
