# Generated by Django 3.0.6 on 2020-06-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='can_add_customer',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('admin', 'admin'), ('guest', 'guest')], db_index=True, max_length=30, verbose_name='role'),
        ),
    ]
