# Generated by Django 3.0.7 on 2020-06-13 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(db_index=True, max_length=4, validators=[django.core.validators.RegexValidator('\\d{4}')], verbose_name='pin'),
        ),
    ]
