# Generated by Django 3.0.7 on 2020-06-17 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilebuyers', to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'buyer',
                'verbose_name_plural': 'buyers',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this sheet should be treated as active. Unselect this instead of deleting sheet.', verbose_name='active status')),
                ('buyers', models.ManyToManyField(related_name='buyersheets', through='notebooks.Buyer', to='accounts.Profile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customersheets', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sheet',
                'verbose_name_plural': 'sheets',
                'unique_together': {('store', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='value')),
                ('operation', models.CharField(choices=[('credit', 'credit'), ('debt', 'debt')], db_index=True, max_length=30, verbose_name='operation')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active. Unselect this instead of deleting record.', verbose_name='active status')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendantrecords', to='accounts.Profile')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheetrecords', to='notebooks.Sheet')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signaturerecords', to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'record',
                'verbose_name_plural': 'records',
            },
        ),
        migrations.AddField(
            model_name='buyer',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheetbuyers', to='notebooks.Sheet'),
        ),
        migrations.AlterUniqueTogether(
            name='buyer',
            unique_together={('sheet', 'profile')},
        ),
    ]
