# Generated by Django 3.0.7 on 2020-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='is_authorized',
        ),
        migrations.AddField(
            model_name='sheet',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this profile should be treated as active. Unselect this instead of deleting profile.', verbose_name='active status'),
        ),
    ]
