# Generated by Django 3.0.7 on 2020-06-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sheet',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='deleted',
        ),
        migrations.AddField(
            model_name='record',
            name='is_deleted',
            field=models.BooleanField(default=True, help_text='Designates whether this record should be treated as deleted. Select this instead of deleting record.', verbose_name='deleted status'),
        ),
    ]
