# Generated by Django 3.0.6 on 2020-06-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_auto_20200601_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='description',
        ),
        migrations.AddField(
            model_name='record',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='note'),
        ),
    ]
