# Generated by Django 3.0.6 on 2020-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_auto_20200604_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='strikethrough',
            field=models.BooleanField(default=False, verbose_name='strikethrough'),
        ),
    ]
