# Generated by Django 3.0.9 on 2020-08-16 18:47

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, verbose_name='data')),
                ('expire_at', models.DateTimeField(verbose_name='expire at')),
                ('status', models.CharField(choices=[('unused', 'unused'), ('used', 'used'), ('discarded', 'discarded')], db_index=True, default='unused', max_length=30, verbose_name='status')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
