# Generated by Django 3.0.6 on 2020-05-23 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbooks', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDebtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(verbose_name='is active')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alloweddebtor_creditor', to=settings.AUTH_USER_MODEL)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alloweddebtor_debtor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'allowed debtor',
                'verbose_name_plural': 'allowed debtors',
                'unique_together': {('creditor', 'debtor')},
            },
        ),
        migrations.AlterField(
            model_name='record',
            name='operation',
            field=models.CharField(choices=[('payment', 'payment'), ('debt', 'debt')], db_index=True, max_length=30, verbose_name='operation'),
        ),
        migrations.DeleteModel(
            name='Whitelist',
        ),
    ]
